add load config subsecion by key
sherifabdlnaby/configuro pull request #5
Opened 2020-12-23 03:42 UTC by lorentz-wu

(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

What does this implement/fix? Explain your changes.
---------------------------------------------------
add load config with key

Does this close any currently open issues?
------------------------------------------
…

Any relevant logs, error output, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
…

2020-12-23 18:37 UTC, sherifabdlnaby commented
This is a welcome addition, can you please add tests? also please delete the `go 1.15`  from `go.mod` because that makes the package not importable to older versions even if it is compatible (happened to me before tho it passes tests)

2020-12-23 23:58 UTC, sherifabdlnaby requested changes
This is a welcome addition, can you please add tests? also please delete the go 1.15 from go.mod because that makes the package not importable to older versions even if it is compatible (happened to me before tho it passes tests)

2020-12-24 02:29 UTC, lorentz-wu commented
> This is a welcome addition, can you please add tests? also please delete the go 1.15 from go.mod because that makes the package not importable to older versions even if it is compatible (happened to me before tho it passes tests)

I removed go 1.15 from go.mod and add testcase LoadKey

2020-12-24 07:28 UTC, merged

2022-09-28 17:02 UTC, MustafaSaber commented on load.go
> +//Load load config with key into supported struct.
I think you need to change this to `// LoadKey` for godocs.